### ISSUE TITLE
failed to getcrumb

### ISSUE THREAD

**Issue by carefreepineapple** [thess/MMM-MktIndex#3]
fresh install, nothing populating.  enabled debug in the module, but only finding this error:
```
{
        module: "MMM-MktIndex",
        debug: true,
        position: "bottom_right",
        config: {
                timeFormat: "DD-MM HH:mm",
                symbols: ["^DJI", "^IXIC", "^GSPC", "^TNX", "CL=F", "EURUSD=X"],
                // Label name for each symbol. When you use `alias`, the number of symbols and aliases should be the same.
                // If value is null or "", symbol string will be used by default.
                alias: ["DOW 30", "Nasdaq", "S&P 500", "10yr Bond", "Crude Oil", "EUR/USD"],
                updateInterval: 180,    // Query interval in seconds
        }
}
```
```
~$ npm start | grep -i mmm-mktindex
[2024-05-31 11:13:47.147] [LOG]   Module helper loaded: MMM-MktIndex
[2024-05-31 11:13:52.472] [LOG]   Connecting socket for: MMM-MktIndex
[2024-05-31 11:14:11.166] [LOG]   [MKTINDEX] Initialized.
[2024-05-31 11:14:16.533] [ERROR] [MKTINDEX] API Error:  request to https://query1.finance.yahoo.com/v1/test/getcrumb failed, reason:
[2024-05-31 11:14:17.027] [INFO]  Checking git for module: MMM-MktIndex
```

**Comment by carefreepineapple** [comment]
local connectivity issue.  Updated timeout from 1500 to 3000 and stocks began to populate.

**Comment by canred1** [comment]
> local connectivity issue. Updated timeout from 1500 to 3000 and stocks began to populate.

Where/how did you change this value, please?

**Comment by carefreepineapple** [comment]
Honestly I have no idea.  I'd look it up for you but my wallboard is down at the moment and I've no immediate plans to bring it back up until I get a rj45 line run through the wall/ceiling, but alas no bandwidth...
Sorry.

**Comment by thess** [comment]
If there is any timeouts to be set, they are not in this module. Perhaps there is one in gadicc/node-yahoo-finance2.

This may be the timeout @carefreepineapple referred to, but it has to do with local client/server communication only and not the YF site data fetching.

 https://github.com/thess/MMM-MktIndex/blob/master/MMM-MktIndex.js#L198
> setTimeout(()=>{
      tr.className = "stock " + ud;
    }, 1500);
